name: exotic-options
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  
  # Core scientific computing
  - numpy>=1.24.0
  - scipy>=1.10.0
  - pandas>=2.0.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  
  # Jupyter ecosystem
  - jupyter>=1.0.0
  - jupyterlab>=4.0.0
  - notebook>=6.5.0
  - ipywidgets>=8.0.0
  
  # Mathematical libraries
  - sympy>=1.11.0
  - statsmodels>=0.14.0
  - scikit-learn>=1.3.0
  
  # Data visualization
  - bokeh>=3.2.0
  
  # Performance libraries
  - numba>=0.57.0
  - cython>=3.0.0
  
  # Development tools
  - pytest>=7.4.0
  - pytest-cov>=4.1.0
  - black>=23.7.0
  - flake8>=6.0.0
  
  # Documentation
  - sphinx>=7.1.0
  - sphinx_rtd_theme>=1.3.0
  
  # Utilities
  - tqdm>=4.65.0
  - joblib>=1.3.0
  
  # Pip dependencies (not available via conda)
  - pip
  - pip:
    - plotly>=5.15.0
    - altair>=5.0.0
    # Financial libraries (uncomment if needed)
    # - quantlib-python>=1.31
    # - yfinance>=0.2.0
    # - pandas-datareader>=0.10.0
